#!/bin/bash

sudo apt install software-properties-common
sudo apt install htop
sudo apt install net-tools
sudo apt install apt-transport-https
sudo apt install curl
sudo apt install plank
sudo apt install python3
sudo apt install tlp tlp-rdw
sudo apt install gnome-tweaks
sudo apt install nautilus-admin
sudo apt install openssh-server
sudo apt install ufw
sudo apt install git
sudo apt install neofetch
sudo apt install gparted
sudo apt install openconnect network-manager-openconnect network-manager-openconnect-gnome openvpn network-manager-openvpn network-manager-openvpn-gnome
sudo apt install libavcodec-extra
sudo apt install gnome-tweak-tool gnome-shell-extensions chrome-gnome-shell
sudo apt install stacer
sudo apt install chromium-browser

#Starting tlp
sudo tlp start

#Reconfiguring dpkg
sudo dpkg-reconfigure libdvd-pkg